#!/bin/bash

cat << EOF
pod
hyperkube
etcd
cluster-kube-apiserver-operator
cluster-policy-controller
cluster-network-operator
multus-cni
egress-router-cni
container-networking-plugins
ovn-kubernetes
network-interface-bond-cni
kube-rbac-proxy
multus-route-override-cni
multus-whereabouts-ipam-cni
cluster-openshift-apiserver-operator
cluster-authentication-operator
cluster-kube-controller-manager-operator
cluster-kube-scheduler-operator
cluster-openshift-controller-manager-operator
cluster-etcd-operator
service-ca-operator
cluster-kube-storage-version-migrator-operator
cluster-dns-operator
network-metrics-daemon
cli
coredns
cluster-machine-approver
cluster-control-plane-machine-set-operator
multus-admission-controller
operator-marketplace
openshift-apiserver
kube-storage-version-migrator
cluster-monitoring-operator
cluster-cloud-controller-manager-operator
insights-operator
operator-lifecycle-manager
cluster-baremetal-operator
cluster-samples-operator
cluster-image-registry-operator
cluster-storage-operator
cluster-config-operator
cluster-ingress-operator
machine-api-operator
machine-config-operator
cluster-csi-snapshot-controller-operator
cluster-node-tuning-operator
cluster-autoscaler-operator
cloud-credential-operator
oauth-proxy
csi-driver-shared-resource-operator
csi-snapshot-validation-webhook
csi-snapshot-controller
prometheus-operator-admission-webhook
prometheus-operator
csi-driver-shared-resource-webhook
csi-node-driver-registrar
csi-driver-shared-resource
prometheus-node-exporter
kube-state-metrics
k8s-prometheus-adapter
telemeter
openshift-state-metrics
prometheus-config-reloader
haproxy-router
route-controller-manager
oauth-apiserver
openshift-controller-manager
console-operator
cli-artifacts
console
oauth-server
docker-registry
prometheus-alertmanager
thanos
prometheus
prom-label-proxy
EOF
